### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OrgestB** [prashanta/godex-printer#1]
Can we use this for usb ports? Thanks

**Comment by prashanta** [comment]
No usb port on the Godex printer cannot be used with this program. It was written to send command on the serial port.

**Comment by OrgestB** [comment]
I've been trying to fix this with usb ports but no success, Is there anything you can suggest in my case? There are no more computers with serial ports. Thanks

**Comment by prashanta** [comment]
In that case you can use  USB-to-Serial converter/cable.It is a straight forward setup, I had a similar situation. However I used with raspberry pi. Hope that helps.

**Comment by drsss** [comment]
@OrgestB I also need to connect from the USB port, have you find any solution?

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @prashanta , thank you very much for sharing your work.

I'm currently designing a solution I have to keep silent about for now , and :+1: 
* If I can make your software work with a GODEX, i will consider forking it, and
* make an actual automated distribution management chain, to turn your software into a rock solid, valid, signed, software dependency, package for most frameworks (a nodejs module, an angular service component, a meteor server module, an npm package, a meteor package, a yo package, a yarn package)   

We can keep contact , I'll be able to speak about it by July 2019.


So this message to thank you, and ask you this :+1: 
* Is it possible to have precision on which model of raspberry pi you used?
* Did you measure `bauds` ? 
* It would be awesome, if you could take A picture or 2, with your phone, of how you connect `raspberry pi`, with your `godex` printer, and a picture of the cable you use (what kind of cable? what kind of connector, example `RS-232`/`DB-25` ?)

**Comment by prashanta** [comment]
Is it possible to have precision on which model of raspberry pi you used?
- Raspberry Pi 3 Model B

Did you measure bauds ?
- No I did not measure. Just used default baud.

It would be awesome, if you could take A picture or 2, with your phone, of how you connect raspberry pi, with your godex printer, and a picture of the cable you use (what kind of cable? what kind of connector, example RS-232/DB-25 ?)
- GODEX DB-9 serial port <---> USB-to-Serial Converter <--> Raspberry Pi USB
